# Generated by Django 3.2.4 on 2021-06-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_player_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='in_game',
            field=models.BooleanField(default=False),
        ),
    ]
